language: java
sudo: false # faster builds

jdk:
  - openjdk11
  - openjdk8

cache:
  directories:
    - $HOME/.m2

install: true

before_script:
  - if [ "$TRAVIS_JDK_VERSION" == "openjdk8" ]; then
    export IMAGE_NAME="openjdk:8u212-jre-alpine";
    fi
  - if [ "$TRAVIS_JDK_VERSION" == "openjdk11" ]; then
    export IMAGE_NAME="openjdk:11-jre-stretch";
    fi

script:
    mvn clean install;
